#!/bin/bash

[[ ! $(type vim) || ! $(type vimtutor) ]] && echo "Need to install vim." && exit 1

mkdir -p ~/.vim/autoload
cp autoload/plug.vim ~/.vim/autoload
ln -fs $PWD/vimrc ~/.vimrc
vim +':PlugInstall' +':q!' +':q!'

echo Add a ~/repos/private/vim/spell directory if you like.

